# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 极妖の博客 #网站标题
subtitle: 人生如逆旅，我亦是行人 #网站副标题
description: 个人博客|JAVA|日常 #网站描述
keywords: 
author: 极妖丶 #您的名字
language: zh-Hans #网站使用的语言
timezone: '' #网站时区。Hexo 默认使用您电脑的时区。时区列表。比如说：America/New_York, Japan, 和 UTC 

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: www.zhangfengcloud.cn #网址
root: / #网站根目录
permalink: :year/:month/:day/:title/ #文章的永久链接格式      :year/:month/:day/:title/
permalink_defaults: 
pretty_urls: 
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source #资源文件，用来存放内容，映射到根目录下的source，在其中的_posts存放*.md文件即可完成博客发布
public_dir: public #公共文件夹，生成的站点文件存放在这个地方
tag_dir: tags #标签文件夹
archive_dir: archives #归档文件架
category_dir: categories #分类文件夹
code_dir: downloads/code #include code文件夹
i18n_dir: :lang #国际化i18n文件夹
skip_render: README.md #跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。

# Writing
new_post_name: :title.md # 新文章的文件名称
default_layout: post #预设布局
titlecase: false # 把标题转换为 title case 
external_link: #在新标签中打开链接
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0 #把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false #显示草稿
post_asset_folder: false #启动 Asset 文件夹
relative_link: false #把链接改为与根目录的相对位址
future: true #显示未来的文章
highlight: #代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator: 
  path: ''
  per_page: 10
  order_by: -date
  
archive_generator: #档案索引
  per_page: 20
  yearly: true
  monthly: true
  
tag_generator: #标签索引
  per_page: 10  

# Category & Tag
default_category: uncategorized #默认分类
category_map: 分类 #分类别名
tag_map: 标签 #标签别名

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD #日期格式
time_format: HH:mm:ss #时间格式
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10 #每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page #分页目录
 
# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: 
exclude: 
ignore: 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
#theme: landscape
#theme: hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo: https://github.com/JiYao-tech/hexo.git
  branch: master

# hexo-neat 静态资源压缩
neat_enable: true 
neat_html: 
  enable: true
  exclude: 
neat_css: 
  enable: false
  exclude: 
    - '*.min.css'
neat_js: 
  enable: true
  mangle: true
  output: 
  compress: 
  exclude: 
    - '*.min.js'

lazyload: 
  enable: true 
  onlypost: false
  loadingImg: 
  
search: 
  path: search.xml
  field: post
  format: html
  limit: 10000  

#豆瓣读书功能    
douban: 
  user: 174999860
  builtin: true
  book: 
    title: '读书系列'
    quote: '书山有路勤为径，学海无涯苦作舟'
  movie: 
    title: '影视系列'
    quote: '当你看过1000部以上的电影，这世界上压根没有什么离奇的事情'
  game: 
    title: '游戏系列'
    quote: '死生在手，变化由心，地不能埋，天不能煞，此之为我命在我也，不在于天。'
  timeout: 10000    
  
#中文链接转拼音
permalink_pinyin: 
  enable: true
  separator: '-'   # default: '-'  
  
live2d: 
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model: 
    use: live2d-widget-model-hibiki
  display: 
    position: left
    width: 150
    height: 350
  mobile: 
    show: true